import { useEffect, useState } from "react";
import { Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { invokeAdminFunction } from "../../lib/adminApi";
import { AdminApiError } from "../../lib/errors";

type Activity = { id: string; action: string; entity_type: string; entity_id: string | null; reason: string | null; request_id: string; created_at: string };
type ProfileResponse = { admin: { id: string; email?: string; createdAt: string; lastSignInAt?: string; appMetadata: Record<string, unknown>; userMetadata: Record<string, unknown>; profile: Record<string, unknown> }; activity: Activity[] };
export function AdminProfilePage() {
  const [data, setData] = useState<ProfileResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  function load() { setLoading(true); setError(null); invokeAdminFunction<ProfileResponse>("admin-profile").then(setData).catch((next: unknown) => setError(next instanceof AdminApiError ? next.message : "Unable to load admin profile.")).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, []);
  return <section className="queue-page" data-aos="fade-up"><div className="page-heading"><div><p className="eyebrow">Account & audit</p><h3>Admin profile</h3><p>Read-only identity, authorization metadata, and actions recorded under this administrator.</p></div><button className="secondary-button" onClick={load} disabled={loading}><RefreshCw size={15} /> Refresh</button></div>{error && <div className="alert alert-error">{error}</div>}{loading && <div className="loading-card"><Loader2 className="spin" size={18} /> Loading admin profile…</div>}{data && <><div className="profile-summary"><div className="profile-summary-icon"><ShieldCheck size={28} /></div><div><p className="eyebrow">Authorized administrator</p><h3>{data.admin.email || "Admin account"}</h3><p>{data.admin.id}</p></div></div><div className="profile-grid"><article className="draft-card"><p className="eyebrow">Authentication</p><dl className="profile-details"><div><dt>Email</dt><dd>{data.admin.email || "—"}</dd></div><div><dt>Created</dt><dd>{new Date(data.admin.createdAt).toLocaleString()}</dd></div><div><dt>Last sign-in</dt><dd>{data.admin.lastSignInAt ? new Date(data.admin.lastSignInAt).toLocaleString() : "—"}</dd></div><div><dt>User ID</dt><dd>{data.admin.id}</dd></div></dl></article><article className="draft-card"><p className="eyebrow">Profile data</p><dl className="profile-details">{Object.entries(data.admin.profile).filter(([key]) => !["id", "created_at", "updated_at"].includes(key)).map(([key, value]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{typeof value === "object" ? JSON.stringify(value) : String(value ?? "—")}</dd></div>)}</dl></article></div><div><p className="eyebrow">Recent activity</p><div className="queue-list">{data.activity.length === 0 ? <div className="empty-state"><h3>No admin actions yet</h3><p>Audited actions performed by this account will appear here.</p></div> : data.activity.map((entry) => <div className="queue-row" key={entry.id}><div><strong>{entry.action}</strong><span>{entry.entity_type} · {entry.entity_id || "No entity ID"}</span></div><div><small>{new Date(entry.created_at).toLocaleString()}</small><span>{entry.reason || "No reason recorded"}</span></div></div>)}</div></div></>}</section>;
}
