import { useEffect, useRef, useState, type ReactNode } from "react";
import { Bot, Send, Trash2, X } from "lucide-react";
import { invokeAdminFunction } from "../../lib/adminApi";

type Message = { id: string; role: "user" | "assistant"; content: string };
const key = "giglify:admin-analysis-chat";
function format(content: string): ReactNode[] { return content.split(/\r?\n/).map((line, index) => { const text = line.trim(); if (!text) return <div key={index} className="h-1" />; const bullet = text.match(/^[-*]\s+(.+)$/); return bullet ? <div key={index} className="admin-ai-bullet"><span>•</span><span>{bullet[1]}</span></div> : <p key={index}>{text}</p>; }); }
export function AdminAiAssistant() {
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState<Message[]>(() => { try { return JSON.parse(localStorage.getItem(key) || "[]") as Message[]; } catch { return []; } }); const [input, setInput] = useState(""); const [sending, setSending] = useState(false); const listRef = useRef<HTMLDivElement>(null);
  useEffect(() => { localStorage.setItem(key, JSON.stringify(messages.slice(-30))); listRef.current?.scrollTo({ top: listRef.current.scrollHeight, behavior: "smooth" }); }, [messages, open]);
  async function send() { const content = input.trim(); if (!content || sending) return; const next = [...messages, { id: crypto.randomUUID(), role: "user" as const, content }]; setMessages(next); setInput(""); setSending(true); try { const result = await invokeAdminFunction<{ reply: string }>("admin-ai-analysis", { message: content, history: messages }); setMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", content: result.reply }]); } catch { setMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", content: "I could not analyze that request. Share a bounded set of operational data and try again." }]); } finally { setSending(false); } }
  return <><button className="admin-ai-launcher" onClick={() => setOpen((value) => !value)} aria-label="Open admin analysis assistant">{open ? <X size={22} /> : <Bot size={22} />}</button>{open && <section className="admin-ai-panel" aria-label="Admin analysis assistant"><header className="admin-ai-header"><div><Bot size={17} /><div><strong>Admin Analyst</strong><small>Read-only data analysis</small></div></div><button className="icon-button" onClick={() => setMessages([])} aria-label="Clear analysis history"><Trash2 size={15} /></button></header><div className="admin-ai-messages" ref={listRef}>{messages.length === 0 && <div className="admin-ai-empty"><Bot size={28} /><strong>Share operational data to analyze</strong><p>Ask for trends, risks, comparisons, or recommended next checks. This assistant cannot mutate records.</p></div>}{messages.map((message) => <div className={`admin-ai-message ${message.role}`} key={message.id}>{message.role === "assistant" ? format(message.content) : message.content}</div>)}{sending && <span className="admin-ai-typing">Analyst is thinking…</span>}</div><footer className="admin-ai-compose"><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="Share data or ask for analysis…" rows={2} /><button className="admin-ai-send" onClick={() => void send()} disabled={sending || !input.trim()} aria-label="Send analysis request"><Send size={16} /></button></footer></section>}</>;
}
