import { useCallback, useEffect, useState } from "react";
import { Loader2, RefreshCw } from "lucide-react";
import { AdminApiError } from "../../lib/errors";
import { applyPaymentAction, fetchPaymentQueue, type Deposit, type Payout } from "./paymentApi";

export function PaymentQueuePage() {
  const [queue, setQueue] = useState<"deposits" | "payouts">("deposits"); const [items, setItems] = useState<(Deposit | Payout)[]>([]); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [note, setNote] = useState(""); const [providerEventId, setProviderEventId] = useState("");
  const load = useCallback(() => { setLoading(true); setError(null); fetchPaymentQueue(queue, status).then((result) => setItems(result.items)).catch((next: unknown) => setError(next instanceof AdminApiError ? next.message : "Unable to load payment queue.")).finally(() => setLoading(false)); }, [queue, status]);
  useEffect(() => { load(); }, [load]);
  async function action(item: Deposit | Payout, nextAction: "approve" | "reject" | "mark_paid") { try { await applyPaymentAction({ entityType: queue === "deposits" ? "verification_deposit" : "payout_request", entityId: item.id, action: nextAction, note, providerEventId: providerEventId || undefined }); setNote(""); setProviderEventId(""); load(); } catch (next: unknown) { setError(next instanceof AdminApiError ? next.message : "Unable to update payment record."); } }
  return <section className="queue-page" data-aos="fade-up"><div className="page-heading"><div><p className="eyebrow">Finance operations</p><h3>{queue === "deposits" ? "Verification deposits" : "Payout requests"}</h3><p>Provider-aware payment actions with explicit reconciliation requirements.</p></div><button className="secondary-button" onClick={load}><RefreshCw size={15} /> Refresh</button></div><div className="queue-filters"><label>Queue<select value={queue} onChange={(e) => { setQueue(e.target.value as "deposits" | "payouts"); setStatus(""); }}><option value="deposits">Verification deposits</option><option value="payouts">Payout requests</option></select></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All</option>{queue === "deposits" ? <><option value="pending">Pending</option><option value="held">Held</option><option value="verified">Verified</option><option value="failed">Failed</option></> : <><option value="requested">Requested</option><option value="under_review">Under review</option><option value="approved">Approved</option><option value="paid">Paid</option><option value="rejected">Rejected</option></>}</select></label><label>Note<input value={note} onChange={(e) => setNote(e.target.value)} placeholder="Reason or internal note" /></label>{queue === "payouts" && <label>Provider event ID<input value={providerEventId} onChange={(e) => setProviderEventId(e.target.value)} placeholder="Required to mark paid" /></label>}</div>{error && <div className="alert alert-error">{error}</div>}{loading && <div className="loading-card overview-loading"><Loader2 className="spin" size={18} /> Loading payments…</div>}{!loading && !error && items.length === 0 && <div className="empty-state"><h3>No records found</h3><p>There are no records matching this payment queue.</p></div>}<div className="queue-list">{items.map((item) => <div className="queue-row" key={item.id}><div><strong>{item.id.slice(0, 14)}…</strong><span>User {item.user_id.slice(0, 8)} · {"amount_usd" in item ? `${item.amount_usd} USD · ${item.method}` : `${item.amount} requested`}</span></div><div><span className="status-pill">{item.status.replace("_", " ")}</span><div className="action-row">{item.status !== "approved" && item.status !== "verified" && <button className="primary-button" onClick={() => action(item, "approve")}>Approve</button>}{!['rejected', 'paid'].includes(item.status) && <button className="danger-button" onClick={() => action(item, "reject")}>Reject</button>}{queue === "payouts" && item.status === "approved" && <button className="secondary-button" onClick={() => action(item, "mark_paid")}>Mark paid</button>}</div></div></div>)}</div></section>;
}
