import { useCallback, useEffect, useState } from "react";
import { Loader2, RefreshCw } from "lucide-react";
import { AdminApiError } from "../../lib/errors";
import { fetchAudit, type AuditEntry } from "./auditApi";

export function AuditLogPage() {
  const [entries, setEntries] = useState<AuditEntry[]>([]); const [entityType, setEntityType] = useState(""); const [action, setAction] = useState(""); const [entityId, setEntityId] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => { setLoading(true); setError(null); fetchAudit({ entityType, action, entityId }).then((result) => setEntries(result.entries)).catch((next: unknown) => setError(next instanceof AdminApiError ? next.message : "Unable to load audit log.")).finally(() => setLoading(false)); }, [entityType, action, entityId]); useEffect(() => { load(); }, [load]);
  return <section className="queue-page" data-aos="fade-up"><div className="page-heading"><div><p className="eyebrow">Investigation trail</p><h3>Audit log</h3><p>Append-only admin actions with before-and-after state.</p></div><button className="secondary-button" onClick={load}><RefreshCw size={15} /> Refresh</button></div><div className="queue-filters"><label>Entity type<input value={entityType} onChange={(e) => setEntityType(e.target.value)} placeholder="payout_request" /></label><label>Action<input value={action} onChange={(e) => setAction(e.target.value)} placeholder="published" /></label><label>Entity ID<input value={entityId} onChange={(e) => setEntityId(e.target.value)} placeholder="Optional UUID" /></label></div>{error && <div className="alert alert-error">{error}</div>}{loading && <div className="loading-card overview-loading"><Loader2 className="spin" size={18} /> Loading audit entries…</div>}{!loading && !error && entries.length === 0 && <div className="empty-state"><h3>No audit entries found</h3><p>Adjust the investigation filters.</p></div>}<div className="queue-list">{entries.map((entry) => <details className="draft-card" key={entry.id}><summary><strong>{entry.action}</strong> · {entry.entity_type} · {new Date(entry.created_at).toLocaleString()}</summary><div className="detail-list"><div><span>Entity</span><strong>{entry.entity_id || "—"}</strong></div><div><span>Actor</span><strong>{entry.actor_user_id}</strong></div><div><span>Request ID</span><strong>{entry.request_id}</strong></div><div><span>Reason</span><p>{entry.reason || "—"}</p></div><div><span>Before</span><pre>{JSON.stringify(entry.before_json, null, 2)}</pre></div><div><span>After</span><pre>{JSON.stringify(entry.after_json, null, 2)}</pre></div></div></details>)}</div></section>;
}
